[package]
name = "sentinel"
version = "0.0.1"
authors = ["Shaurya Rawat <rawatshaurya1994@gmail.com>"]
categories = ["Systemd", "Services"]
edition = "2021"
rust-version = "1.67.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
