name: release

on:
  push:
    tags:
      - "*"
    branches:
      - master

jobs:
  check-version:
    name: Check version validity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check tag format
        id: check-tag-format
        run: |
          tag_version=$(printf "%q" ${{ github.ref_name }})

          if [[ $tag_version =~ "^v[0-9]+\.[0-9]+\.[0-9]+$" ]]; then
            echo "stable=true" >> $GITHUB_OUTPUT
          else
            echo "stable=false" >> $GITHUB_OUTPUT
          fi
      - name: Check tag version
        if: steps.check-tag-format.outputs.stable == 'true'
        run: bash .github/scripts/check-tag-version.sh

  publish-release:
    name: Publish release for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: check-version
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64-unknown-linux-gnu
          - x86_64_unknown-linux-musl
          - aarch64-apple-darwin
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Cross
        run: cargo install cross --target ${{ matrix.arch }}
      - name: Build for ${{ matrix.arch }}
        run: cross build --target ${{ matrix.arch }} --release
      - name: Publish release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.arch }}/release/sentinel
          asset_name: sentinel_${{ matrix.arch }}
          tag: ${{ github.ref }}
