name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  check-version:
    name: Check version validity
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check tag format
        id: check-tag-format
        run: |
          tag_version=$(printf "%q" ${{ github.ref_name }})

          if [[ $tag_version =~ "^v[0-9]+\.[0-9]+\.[0-9]+$" ]]; then
            echo "stable=true" >> $GITHUB_OUTPUT
          else
            echo "stable=false" >> $GITHUB_OUTPUT
          fi
      - name: Check tag version
        if: steps.check-tag-format.outputs.stable == 'true'
        run: bash .github/scripts/check-tag-version.sh

  publish-release:
    name: Publish release for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    needs: check-version
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-apple-darwin
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          target: ${{ matrix.arch }}
          override: true
      - name: Install Cross
        if: ${{ matrix.arch }} != 'aarch64-apple-darwin'
        run: cargo install cross --target ${{ matrix.arch }}
      - name: Build for ${{ matrix.arch }}
        if: ${{ matrix.arch }} != 'aarch64-apple-darwin'
        run: cross build --target ${{ matrix.arch }} --release
      - name: Build for Apple silicon
        if: ${{ matrix.arch }} == 'aarch64-apple-darwin'
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.arch }}
      - name: Publish release
        uses: svenstaro/upload-release-action@2.5.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.arch }}/release/sentinel
          asset_name: sentinel_${{ matrix.arch }}
          tag: ${{ github.ref }}
